export enum LegalTextTypeEnum {
  "SOCIAL_LAW" = "SOCIAL_LAW",
  "TAX_LAW " = "TAX_LAW",
  "INSURANCE_LAW" = "INSURANCE_LAW",
  "MARITIME_LAW" = "MARITIME_LAW",
  "CORPORATE_LAW" = "CORPORATE_LAW",
  "ADMINISTRATIVE_LAW" = "ADMINISTRATIVE_LAW",
  "COMMERCIAL_LAW" = "COMMERCIAL_LAW",
  "CRIMINAL_BUSINESS_LAW" = "CRIMINAL_BUSINESS_LAW",
}

export enum DocumentTypeEnum {
  "CONSTITUTION" = "CONSTITUTION",
  "DECREES" = "DECREES",
  "TREATIES" = "TREATIES",
  "ORDERS" = "ORDERS",
  "LAWS" = "LAWS",
  "JURISPRUDENCE" = "JURISPRUDENCE",
  "ORDINANCES" = "ORDINANCES",
  "CIRCULARS" = "CIRCULARS",
}

export enum BlocEnum {
  "REGULATORY" = "REGULATORY",
  "LEGISLATIVE" = "LEGISLATIVE",
}

export enum ActionEnum {
  "PRECISION" = "PRECISION",
  "MODIFICATION" = "MODIFICATION",
  "APPLICATION" = "APPLICATION",
}

export enum StatusEnum {
  "ROVOKED" = "ROVOKED",
  "APPLICABLE" = "APPLICABLE",
}

export enum EvaluationNoteEnum {
  "BAD" = "BAD",
  "USEFUL" = "USEFUL",
  "GREAT" = "GREAT",
  "NOT_SATISFIED" = "NOT_SATISFIED",
  "SATISFIED" = "SATISFIED",
}
